# mkdocs.yml
site_name: Brightest Path Library

theme:
  name: "material"
  features:
    - content.code.copy
    - navigation.instant

plugins:
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Overview: overview.md
  - Getting Started:
    - installation.md
    - quickstart_guide.md
  - API Documentation: api_docs.md
  - Tutorials: 
    - simple_notebook.ipynb
    - threading_notebook.ipynb
  - About: about.md
 
